[package]
name = "linz_S3"
version = "0.1.0"
edition = "2021"

[dependencies]
stac = { version = "0.11.1", features = ["object-store", "object-store-all", "object-store-aws"] }
tokio = { version = "1.43.0", features = ["full", "rt-multi-thread"] }
